### ISSUE TITLE
Testing Practices

### ISSUE THREAD

**Issue by rachidlamouri** [normal-devs/klicker-knight#7]
## Arrange, Act, Assert (AAA) Pattern

I always link a new blog when I write this. So [here's a new one](http://wiki.c2.com/?ArrangeActAssert). Helps separate tests setup from assertions. Prevents assertions from affecting each other.

## Semantic `context` and `describe`
Use `describe` to name a file, module, component, function, unit or **thing** that you're testing. Use `context` to explain the situation that you're putting the **thing** through.

## Use `context` for test cases and `it` for assertions
Mocha is designed so that `it` represents a test case. This works great for functions but kind of poorly for more complex units. Grouping multiple `it` blocks under a single `context` allows for multiple simultaneous assertions and better organization of setup and teardown. It also permits readability by separating the setup explanation from the results.

**Exception**: A standalone test case with no setup or teardown can be in an isolated `it`

## Avoid beforeEach and afterEach outside of testing pure units
This makes it too easy to mix unrelated setup and teardown because it affects all nested `it` blocks.

## Place `after` immediately after `before`
Makes it easier to compare and debug

## Simple present tense assertions
Provides consistent and concise wording for assertions

**Comment by jshemas** [comment]
Can you add a example of `AAA`?

**Comment by jshemas** [comment]
semantic-mocha was added in https://github.com/normal-devs/klicker-knight/pull/17

**Comment by rachidlamouri** [comment]
It looks like semantic-mocha covers everything but the last one. We will have to enforce "Simple present tense assertions" through code review.
